name: 'CI/CD'

on:
  push:
    branches:
      - main
    paths:
      - 'front-end/**'

env:
  AWS_REGION: us-east-2

jobs:
  frontend:
    name: 'Frontend'
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Install Dependencies'
        run: npm install
        working-directory: './front-end'
        
      # - name: 'Run Tests'
      #   run: npm test
      #   working-directory: './front-end'

      - name: 'Build'
        run: npm run build
        working-directory: './front-end'
        
      # Configure AWS Credentials
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      # Deploy to S3
      - name: 'Deploy to S3'
        run: |
          aws s3 sync ./front-end/build/ s3://rrjamal
      
      # Invalidate CloudFront Distribution
      - name: 'Invalidate CloudFront Distribution'
        run: |
          aws cloudfront create-invalidation --distribution-id ESNOZ1ZUNIC64 --paths "/*"