name: restapi-deployment

on:
  push:
    branches:
      - main
    paths:
      - 'restapi/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Update Database Connection
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB: ${{ secrets.DB }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: cd restapi/ && python3 update_config.py
      - name: Docker build
        run: cd restapi/ && docker build -t restapi . && docker tag restapi:latest 369635783248.dkr.ecr.us-east-2.amazonaws.com/restapi:latest && docker push 369635783248.dkr.ecr.us-east-2.amazonaws.com/restapi:latest
